//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catharsis.Web.Widgets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catharsis.Web.Widgets.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;disqus_thread&quot;&gt;&lt;/div&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    var disqus_shortname = &quot;{0}&quot;;
        ///&lt;/script&gt;
        ///&lt;noscript&gt;Please enable JavaScript to view the &lt;a href=&quot;http://disqus.com/?ref_noscript&quot;&gt;comments powered by Disqus.&lt;/a&gt;&lt;/noscript&gt;
        ///&lt;a href=&quot;http://disqus.com&quot; class=&quot;dsq-brlink&quot;&gt;comments powered by &lt;span class=&quot;logo-disqus&quot;&gt;Disqus&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string disqus_comments {
            get {
                return ResourceManager.GetString("disqus_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///(function(d, s, id)
        /// {{
        ///  var js, fjs = d.getElementsByTagName(s)[0];
        ///  if (d.getElementById(id)) return;
        ///  js = d.createElement(s);
        ///  js.id = id;
        ///  js.src = &quot;//connect.facebook.net/en_US/all.js#xfbml=1&amp;appId={0}&quot;;
        ///  fjs.parentNode.insertBefore(js, fjs);
        ///}}(document, &apos;script&apos;, &apos;facebook-jssdk&apos;));
        ///&lt;/script&gt;.
        /// </summary>
        internal static string facebook_initialize {
            get {
                return ResourceManager.GetString("facebook_initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///    (function (i, s, o, g, r, a, m) {{
        ///        i[&apos;GoogleAnalyticsObject&apos;] = r;
        ///        i[r] = i[r] || function () {{
        ///            (i[r].q = i[r].q || []).push(arguments)
        ///        }}, i[r].l = 1 * new Date();
        ///        a = s.createElement(o),
        ///                m = s.getElementsByTagName(o)[0];
        ///        a.async = 1;
        ///        a.src = g;
        ///        m.parentNode.insertBefore(a, m)
        ///    }})(window, document, &apos;script&apos;, &apos;//www.google-analytics.com/analytics.js&apos;, &apos;ga&apos;);
        ///
        ///    ga(&quot;crea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string google_analytics {
            get {
                return ResourceManager.GetString("google_analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///  var idcomments_acct = &quot;{0}&quot;;
        ///  var idcomments_post_id = &quot;{1}&quot;;
        ///  var idcomments_post_url = &quot;{2}&quot;;
        ///  var idcomments_post_title = &quot;{3}&quot;;
        ///&lt;/script&gt;
        ///&lt;span id=&quot;IDCommentsPostTitle&quot; style=&quot;display:none&quot;&gt;&lt;/span&gt;
        ///&lt;script src=&quot;http://www.intensedebate.com/js/genericCommentWrapperV2.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;.
        /// </summary>
        internal static string intensedebate_comments {
            get {
                return ResourceManager.GetString("intensedebate_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///  var idcomments_acct = &quot;{0}&quot;;
        ///  var idcomments_post_id = &quot;{1}&quot;;
        ///  var idcomments_post_url = &quot;{2}&quot;;
        ///  var idcomments_post_title = &quot;{3}&quot;;
        ///&lt;/script&gt;
        ///&lt;span id=&quot;IDCommentsPostTitle&quot; style=&quot;display:none&quot;&gt;&lt;/span&gt;
        ///&lt;script src=&quot;http://www.intensedebate.com/js/genericLinkWrapperV2.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;.
        /// </summary>
        internal static string intensedebate_link {
            get {
                return ResourceManager.GetString("intensedebate_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Yandex.Metrika informer --&gt;
        ///&lt;a href=&quot;http://metrika.yandex.ru/stat/?id=12066574&amp;amp;from=informer&quot; target=&quot;_blank&quot; rel=&quot;nofollow&quot;&gt;
        ///  &lt;img src=&quot;//bs.yandex.ru/informer/12066574/3_1_FFFFFFFF_EFEFEFFF_0_pageviews&quot; style=&quot;width:88px; height:31px; border:0;&quot; alt=&quot;Яндекс.Метрика&quot; title=&quot;Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)&quot; onclick=&quot;try
        ///  {{
        ///    Ya.Metrika.informer({{i: this, id: {0}, lang: &apos;{1}&apos;}});
        ///    return false
        ///  }}
        ///  catch (e)
        ///  {{
        ///  }}&quot;/&gt;
        ///&lt;/a&gt;
        ///&lt;!--  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string yandex_analytics {
            get {
                return ResourceManager.GetString("yandex_analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///if (window.Ya &amp;&amp; window.Ya.Share)
        ///{
        ///  Ya.Share.update();
        ///}
        ///else
        ///{
        ///  (function ()
        ///  {
        ///    if (!window.Ya)
        ///    {
        ///      window.Ya = {}
        ///    };
        ///
        ///    Ya.STATIC_BASE = &apos;http:\/\/yandex.st\/wow\/2.15.3\/static&apos;;
        ///    Ya.START_BASE = &apos;http:\/\/my.ya.ru\/&apos;;
        ///    var shareScript = document.createElement(&quot;script&quot;);
        ///    shareScript.type = &quot;text/javascript&quot;;
        ///    shareScript.async = &quot;true&quot;;
        ///    shareScript.charset = &quot;utf-8&quot;;
        ///    shareScript.src = Ya.STATIC_BASE + &quot;/js/api/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string yandex_like {
            get {
                return ResourceManager.GetString("yandex_like", resourceCulture);
            }
        }
    }
}
