<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Catharsis.Web.Widgets</AssemblyName>
    <RootNamespace>Catharsis.Web.Widgets</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Version>1.0</Version>
    <Company>Prokhor Ozornin &lt;prokhor.ozornin@yandex.ru&gt;</Company>
    <Authors>Prokhor Ozornin &lt;prokhor.ozornin@yandex.ru&gt;</Authors>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <DocumentationFile>API.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="packages.config" />
    <None Remove="web.config" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="packages.config" />
    <Content Include="web.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Catharsis.Extensions">
      <HintPath>\\NAS\build\NET\Catharsis.Extensions\net9.0\Catharsis.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="resources.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>resources.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
